version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: beyza_movie_app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
